config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root to: 'home#index'
	resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ActiveRecord::Base
		validates_presence_of :label, :starting_date, :month_frequency, :day
		validate :month_frequency, :if => :is_actual_frequency?
		validate :day, :if => :is_month_day?


		def next_delivery_date
			EventDetail.new(event: self).generate.first
		end

		private

		# this will validate that the month frequency is greater than 0
		def is_actual_frequency?
			if !!month_frequency && month_frequency < 1
				errors.add(:month_frequency, " must be greater than 0")
			end
		end

		#validates that the input will be between 1 and 31
		def is_month_day?
			if !!self.day
				if self.day > 31
					errors.add(:day, " number cannot be greater than 31.")
				elsif self.day < 1
					errors.add(:day, " number cannot be less than one.")
				end
			end
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :find_event, only:[:edit, :update, :show, :destroy]

	def index
		@events = Event.all
	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(event_params)
		if @event.save
			redirect_to events_path
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @event.update(event_params)
			redirect_to events_path
		else
			render :edit
		end
	end

	def show
		@next_four_dates = EventDetail.new(event: @event).generate
	end

	def destroy
		@event.destroy
		redirect_to events_path
	end

	private

	def event_params
		params.require(:event).permit(:label, :starting_date, :month_frequency, :day)
	end

	def find_event
		@event = Event.find(params[:id])
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_event.html.erb
<h2>
	<%= link_to event.label, event_path(event) %>
	Next delivery date <%= event.next_delivery_date %>  ||
	<%= link_to "Edit", edit_event_path(event) %>
	<%= link_to "Delete", event_path(event), method: :delete, data:{confirm:'Are you sure you want to delete this event?'} %>
</h2>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
	<div>
		<% if @event.errors.any? %>
			<% @event.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		<% end %>
	</div>
	<div>
		<%= f.label :label %>
		<%= f.text_field :label %>
	</div>
	<div>
		<%= f.label :starting_date %>
		<%= f.date_field :starting_date %>
	</div>

	<div>
		<%= f.label :month_frequency %>
		<%= f.number_field :month_frequency, in:1.0..1000.0, step: 1 %>
	</div>

	<div>
		<%= f.label :day %>
		<%= f.select :day, (1..31) %>
	</div>


	<%= f.submit %>
<% end %>

app/views/events/edit.html.erb
<h1>Edit <%= @event.label %> Event</h1>
<%= render 'form' %>

app/views/events/index.html.erb
<center>
	<% if @events.count > 0 %>
		<%= render partial: 'event', collection: @events %>
	<% else %>
		<h2>No Events Yet</h2>
	<% end %>

	<h3>
		<%= link_to "Add New Event", new_event_path() %>
	</h3>	
</center>

app/views/events/new.html.erb
<h1>New Event</h1>
<%= render 'form' %>

app/views/events/show.html.erb
<h1> <%= @event.label %></h1>

<h2>Next four delivery dates are:</h2>
<div>
	<ul>
		<% @next_four_dates.each do |date|  %>
			<li> <%= date %> </li>
		<% end %>
	</ul>
</div>

app/views/home/index.html.erb
<center>
	<h1>Welcome to the Reoccurring Events Calculator!</h1>
	<h2> <%= link_to "Create New Event", new_event_path %> or <%= link_to "See Live Events", events_path %> </h2>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TlReoccurringEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>